import { AnalyticsDataPoint, IntegrationActivity } from '@/types/analytics';

export const exportToCSV = (data: AnalyticsDataPoint[], filename: string): void => {
  const headers = ['Date', 'Conversations', 'Messages', 'API Calls'];
  const rows = data.map(d => [d.date, d.conversations, d.messages, d.apiCalls]);
  
  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.join(','))
  ].join('\n');
  
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${filename}.csv`;
  link.click();
  URL.revokeObjectURL(link.href);
};

export const exportIntegrationsToCSV = (data: IntegrationActivity[], filename: string): void => {
  const headers = ['Integration', 'Conversations', 'Messages'];
  const rows = data.map(d => [d.name, d.conversations, d.messages]);
  
  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.join(','))
  ].join('\n');
  
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${filename}.csv`;
  link.click();
  URL.revokeObjectURL(link.href);
};

export const generatePDFReport = (
  data: AnalyticsDataPoint[],
  integrations: IntegrationActivity[],
  timeRange: string
): void => {
  // Calculate totals
  const totals = data.reduce(
    (acc, d) => ({
      conversations: acc.conversations + d.conversations,
      messages: acc.messages + d.messages,
      apiCalls: acc.apiCalls + d.apiCalls,
    }),
    { conversations: 0, messages: 0, apiCalls: 0 }
  );

  const dateRange = data.length > 0 
    ? `${formatDate(data[0].date)} - ${formatDate(data[data.length - 1].date)}`
    : 'No data';

  // Create HTML content for PDF
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>GhostWorker Analytics Report</title>
      <style>
        body { font-family: system-ui, -apple-system, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
        h1 { color: #1a1a1a; border-bottom: 2px solid #6366f1; padding-bottom: 10px; }
        h2 { color: #374151; margin-top: 30px; }
        .summary { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin: 20px 0; }
        .card { background: #f9fafb; border-radius: 8px; padding: 20px; text-align: center; }
        .card-value { font-size: 32px; font-weight: bold; color: #1a1a1a; }
        .card-label { color: #6b7280; margin-top: 5px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
        th { background: #f3f4f6; font-weight: 600; }
        .meta { color: #6b7280; font-size: 14px; margin-bottom: 20px; }
        .footer { margin-top: 40px; color: #9ca3af; font-size: 12px; text-align: center; }
      </style>
    </head>
    <body>
      <h1>Analytics Report</h1>
      <p class="meta">Period: ${dateRange} (Last ${timeRange} days)</p>
      
      <div class="summary">
        <div class="card">
          <div class="card-value">${totals.conversations.toLocaleString()}</div>
          <div class="card-label">Total Conversations</div>
        </div>
        <div class="card">
          <div class="card-value">${totals.messages.toLocaleString()}</div>
          <div class="card-label">Total Messages</div>
        </div>
        <div class="card">
          <div class="card-value">${totals.apiCalls.toLocaleString()}</div>
          <div class="card-label">API Calls</div>
        </div>
      </div>

      <h2>Daily Breakdown</h2>
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Conversations</th>
            <th>Messages</th>
            <th>API Calls</th>
          </tr>
        </thead>
        <tbody>
          ${data.slice(-10).map(d => `
            <tr>
              <td>${formatDate(d.date)}</td>
              <td>${d.conversations}</td>
              <td>${d.messages}</td>
              <td>${d.apiCalls}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <h2>Integration Performance</h2>
      <table>
        <thead>
          <tr>
            <th>Integration</th>
            <th>Conversations</th>
            <th>Messages</th>
          </tr>
        </thead>
        <tbody>
          ${integrations.map(i => `
            <tr>
              <td>${i.name}</td>
              <td>${i.conversations}</td>
              <td>${i.messages.toLocaleString()}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <div class="footer">
        Generated by GhostWorker on ${new Date().toLocaleDateString()}
      </div>
    </body>
    </html>
  `;

  // Open print dialog with the report
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.onload = () => {
      printWindow.print();
    };
  }
};

const formatDate = (dateStr: string): string => {
  return new Date(dateStr).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
};
